name: CheckSwitch
description: 'GitHub Action using check lists as switches for more actions'
author: Kineolyan

# Define your inputs here.
inputs:
  github_token:
    description: Token for the GitHub API.
    default: ${{ github.token }}
  delay:
    description: 'Delay before processing the Pull Request body'
    required: false
    default: '10000'

# Define your outputs here.
outputs:
  report:
    description: 'JSON reporting the active switches'

runs:
  using: node20
  main: dist/index.js
