name: Test action live

on:
  pull_request:
    types: 
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  test-bash:
    name: Test consuming output from bash
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Read switches
        id: read-switches
        uses: ./
        with:
          delay: 100

      - name: Print Output
        id: output
        run: echo "${{ steps.read-switches.outputs.report }}"

  # test-action:
  #   name: GitHub Actions Test
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       id: checkout
  #       uses: actions/checkout@v4

  #     - name: Test Local Action
  #       id: test-action
  #       uses: ./
  #       with:
  #         milliseconds: 1000

  #     - name: Print Output
  #       id: output
  #       run: echo "${{ steps.test-action.outputs.time }}"
